#!/bin/sh
# ----------------------------------------------------------------------------
#  Copyright 2001-2004 The Apache Software Foundation.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#       http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------

#   Copyright (c) 2001-2002 The Apache Software Foundation.  All rights
#   reserved.

#  Modified by Matteo Merli <matteo.merli@gmail.com> 
#  for RtspProxy
#
#  $Id: rtspproxy 261 2005-10-28 19:09:20Z merlimat $
#  $URL: http://svn.berlios.de/svnroot/repos/rtspproxy/tags/3.0-ALPHA2/src/resources/scripts/rtspproxy $

if [ -f /etc/rtspproxyrc ] ; then
  . /etc/rtspproxyrc
fi

if [ -f "$HOME/.rtspproxyrc" ] ; then
  . "$HOME/.rtspproxyrc"
fi

# OS specific support.  $var _must_ be set to either true or false.
cygwin=false;
darwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  Darwin*) darwin=true 
           if [ -z "$JAVA_VERSION" ] ; then
             JAVA_VERSION="CurrentJDK"
           else
             echo "Using Java version: $JAVA_VERSION"
           fi
           if [ -z "$JAVA_HOME" ] ; then
             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
           fi
           ;;
esac

if [ -z "$RTSPPROXY_HOME" ] ; then
  # try to find RTSPPROXY
  if [ -d /opt/rtspproxy ] ; then
    RTSPPROXY_HOME=/opt/rtspproxy
  fi

  if [ -d "$HOME/rtspproxy" ] ; then
    RTSPPROXY_HOME="$HOME/rtspproxy"
  fi

  ## resolve links - $0 may be a link to maven's home
  PRG="$0"
  saveddir=`pwd`

  # need this for relative symlinks
  PRGDIR=`dirname "$PRG"`
  cd "$PRGDIR"

  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '.*/.*' > /dev/null; then
  PRG="$link"
    else
  PRG="$PRGDIR/$link"
    fi
  done

  RTSPPROXY_HOME="$PRGDIR"

  # make it fully qualified
  RTSPPROXY_HOME=`cd "$RTSPPROXY_HOME" && pwd`

  cd "$saveddir"
fi

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
  [ -n "$RTSPPROXY_HOME" ] &&
    RTSPPROXY_HOME=`cygpath --unix "$RTSPPROXY_HOME"`
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
  [ -n "$CLASSPATH" ] &&
    CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
      # IBM's JDK on AIX uses strange locations for the executables
      JAVACMD="$JAVA_HOME/jre/sh/java"
    else
      JAVACMD="$JAVA_HOME/bin/java"
    fi
  else
    JAVACMD=java
  fi
fi

if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly."
  echo "  We cannot execute $JAVACMD"
  exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
  echo "Warning: JAVA_HOME environment variable is not set."
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  [ -n "$M2_HOME" ] &&
    RTSPPROXY_HOME=`cygpath --path --windows "$RTSPPROXY_HOME"`
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
  [ -n "$HOME" ] &&
    HOME=`cygpath --path --windows "$HOME"`
fi

RTSPPROXY_CLASSPATH="."
LIST="$(ls ${RTSPPROXY_HOME}/lib/*.jar)"
for i in $LIST; 
do
    RTSPPROXY_CLASSPATH=$RTSPPROXY_CLASSPATH:$i
done

exec "$JAVACMD" \
  $RTSPPROXY_OPTS \
  -server \
  -classpath "${RTSPPROXY_CLASSPATH}" \
  "-Drtspproxy.home=${RTSPPROXY_HOME}"  \
  rtspproxy.Main $@

